In [10]:
# liner array
from array import *
#from  numpy import *

a = array('i',[1,2])
print(a)

b = array('i',[])
t = int(input('how many elements'))

for i in range(t):
     b.append(int(input('enter elements  : ')))
print(b)

print(a+b)
from numpy import matrix
a1=matrix(a)
print(a1)
b1=matrix([[1,2],[2,3]])
print(shape(b1))
print(b1)

print(a1*b1)

array('i', [1, 2])
how many elements2
enter elements  : 5
enter elements  : 4
array('i', [5, 4])
array('i', [1, 2, 5, 4])
[[1 2]]
(2, 2)
[[1 2]
 [2 3]]
[[5 8]]


In [31]:
a=[]
n = int(input("how many elements "))
for i in range(n):
    a.append((int(input(" enter elements "))))
print(a)
p, m =[ int(i) for i in input(" enter position and item to insert ").split(',')]
print(p , m)   
n=n
print(n)
while(p<n):
    a[p+1]=a[p]
    p+=1
#a[p-1]=m    
print(a)

    

how many elements 3
 enter elements 4
 enter elements 5
 enter elements 6
[4, 5, 6]
 enter position and item to insert 0,1
0 1
3


IndexError: list assignment index out of range

In [4]:
# deletion in an linear array
from array import *
a = array('i', [])

b = int(input('how much elements'))
for i in range(b):
    a.append(int(input(" enter the elements :  ")))
print(a)


n = int(input('enter element u want to delete  '))

for i in range(b):
    print(a[i])
    if n==a[i]:
        c=i
        #break
#a.pop(c)
#a.remove(n)

print(a)

how much elements5
 enter the elements :  4
 enter the elements :  5
 enter the elements :  6
 enter the elements :  8
 enter the elements :  5
array('i', [4, 5, 6, 8, 5])
enter element u want to delete  6
array('i', [4, 5, 8, 5])


In [27]:
from array import *
a = array('i', [])

b = int(input('how much elements'))
for i in range(b):
    a.append(int(input(" enter the elements :  ")))
print(a)


n = int(input('enter element u want to delete  '))
for i in range(b):
        if a[i]==n:
            c = i 
            break
d = c
b=b-1
print(b, d)
while(d< b):
        a[d]=a[d+1]         
        d+=1
for i in range(b):
        print(a[i])

how much elements3
 enter the elements :  4
 enter the elements :  5
 enter the elements :  6
array('i', [4, 5, 6])
enter element u want to delete  5
2 1
4
6


In [5]:
from numpy import *

m, n = [int(x) for x in input('enter number of rows and column').split(',')]

a=zeros((m, n), dtype=int)

for i in range(0,m):
    for j in range(0,n):
        a[i][j]=int(input('enter elements  '))

print(a)        

enter number of rows and column2,2
enter elements  2
enter elements  2
enter elements  2
enter elements  2
[[2 2]
 [2 2]]


In [7]:
from numpy import *
import array

m, n = [int(x) for x in input('enter number of rows and column').split(',')]

a1=zeros((m, n), dtype=int)


for i in range(0,m):
    for j in range(0,n):
        a1[i][j]=int(input('enter elements  '))

print(a1)        

# second mathod

str=input('enter second matrix elements  ')
print(str)
x= reshape(matrix(str), (m, n))
print(x)

enter number of rows and column2,2
enter elements  5
enter elements  4
enter elements  8
enter elements  7
[[5 4]
 [8 7]]
enter second matrix elements  5 4 8 7 
5 4 8 7 
[[5 4]
 [8 7]]


In [12]:
n = int(input('how many elements  : ')) # to find max and min element
a=[]
for i in range(n):
    a.append(int(input('elements  : ')))
print(a)    
m=a[0]

for i in range(1,n):
    if a[i]>m:
        m = a[i]   
print(m)     

min=a[0]
for i in range(1,n):
    if min>a[i]:
        min=a[i]
print(min)    

how many elements  : 10
elements  : 9
elements  : 2
elements  : 8
elements  : 6
elements  : 7
elements  : 3
elements  : 4
elements  : 1
elements  : 8
elements  : 9
[9, 2, 8, 6, 7, 3, 4, 1, 8, 9]
9
1


In [13]:
n = int(input('how many elements  : ')) # to find  max and min element
a=[]
for i in range(n):
    a.append(int(input('elements  : ')))
print(a)    
m=a[0]

for i in range(1,n):
    if a[i]>m:
        m = a[i]   
print(m) 
for i in range(1,n):
    if a[i]>m and  a.max(a):
        m=a[i]
print(m)        
    

min=a[0]
for i in range(1,n):
    if min>a[i]:
        min=a[i]
print(min)    

how many elements  : 3
elements  : 5
elements  : 4
elements  : 6
[5, 4, 6]
6
6
4


In [3]:
n = int(input('how many elements  : ')) # to find  second max element
a=[]
for i in range(n):
    a.append(int(input('elements  : ')))
print(a)    
m=a[0]

for i in range(1,n):
    if a[i]>m:
        m = a[i]   
print(m) 

for i in range(1,n):
    if a[i]>m:
        m=a[i]
sm=0
i=0
for i in range(1,n):
    if a[i]>sm and a[i]<m:
        sm=a[i]
print('second max', sm)        
    

min=a[0]
for i in range(1,n):
    if min>a[i]:
        min=a[i]
print(min)   



how many elements  : 5
elements  : 4
elements  : 5
elements  : 5
elements  : 2
elements  : 6
[4, 5, 5, 2, 6]
6
second max 5
2


In [33]:
# reverse of array
from array import *

a=[]
n=int(input('how many '))
for i in range(n):
    a.append(int(input('enter : ')))
print(a) 
a1=a[::-1]
print(a1)

how many 3
enter : 4
enter : 5
enter : 6
[4, 5, 6]
[6, 5, 4]


In [1]:
from array import *

a=[]
n=int(input('how many '))
for i in range(n):
    a.append(int(input('enter : ')))
print(a) 


how many 5
enter : 4
enter : 5
enter : 6
enter : 7
enter : 8
[4, 5, 6, 7, 8]


In [1]:
import array
a=[]
n=int(input())
for i in range(n):
      a.append([int(x) for x in input().split()])
print(a)    
a1=a[::-1] # reverse
print(a1)

3
4
5
6
[[4], [5], [6]]
[[6], [5], [4]]


In [38]:
import sys


n = int(input().strip())
arr = [int(arr_temp) for arr_temp in input().strip().split(' ')]
print(arr)

for i in range(len(arr)):
    print(str(arr[-i-1]), end=" ")


4
4 5 6 1 2
[4, 5, 6, 1, 2]
2 1 6 5 4 

In [39]:
n = int(input('how many'))
a=[]
for i in range(n):
    a.append(int(input('enter  ')))
print(a) 
dd=len(a)
print(dd)
b=[]
for i in range(dd):
    b.append(a[-i-1])
print(b)
  
   

how many3
enter  45
enter  6
enter  4
[45, 6, 4]
3
[4, 6, 45]


In [3]:
# maximum sum of hourglass in an array
import numpy as np
r ,c=[int(x) for x in input().split()]
a=np.zeros((r, c),dtype=int)
print( r , c)
for i in range(0,r):
    for j in range(0,c):
        a[i][j]=int(input('enter  '))
print(a) 
total=0
max_total=-12233445566
for i in range(len(a)):
    for j in range(len(a[i])):
        if j+2<4 and i+2<4:
            total = a[i][j] + a[i][j+1] + a[i][j+2]+a[i+1][j+1]+a[i+2][j]+a[i+2][j+1]+a[i+2][j+2]
            if max_total < total:

                max_total = total
print(max_total)
    



4 4
4 4
enter  1
enter  2
enter  3
enter  4
enter  5
enter  6
enter  7
enter  8
enter  9
enter  0
enter  9
enter  8
enter  7
enter  6
enter  5
enter  4
[[1 2 3 4]
 [5 6 7 8]
 [9 0 9 8]
 [7 6 5 4]]
45


In [42]:
  a = []

for _ in range(6):
    ar=[int(x) for x in input().strip().split(' ')]
    a.append(ar)

total=0
mtotal=-1234567
for i in range(len(a)):
    for j in range(len(a[i])):
        if (j+2<6) and (i+2<6):
            total= a[i][j]+a[i][j+1]+a[i][j+2]+a[i+1][j+1]+a[i+2][j]+a[i+2][j+1]+a[i+2][j+2]
        if mtotal<total:
            mtotal=total
print(mtotal)           

5
4
7
8
9
6


IndexError: list index out of range

In [40]:
n=int(input('neter age : '))
if n>=18:
    print('u can vote')
else:  
    print(' u can not ')
    

neter age : 4
 u can not 


In [3]:
# to rotate an array of n size by d elements
import numpy as np
a=[]
n=int(input('enter the size of array : '))
for i in range(n):
    a.append(int(input('enter : ')))
print(a)    

#m1
d=int(input('enter the number of elements to rotate : '))
temp=[]
for i in range(d):
    temp.append(a[i])
print(temp) 
for i in range(n-d):
    a[i]=a[i+d]
for i in range(d):
    a[n-d+i]=temp[i]
print(a)
#m2 # rotate elements one by one by d times
for i in range(d):
    temp=a[0]
    for i in range(n-1):
        a[i]=a[i+1]
    a[n-1]=temp    
print('m2', a)        
    


enter the size of array : 5
enter : 4
enter : 7
enter : 8
enter : 9
enter : 6
[4, 7, 8, 9, 6]
enter the number of elements to rotate : 2
[4, 7]
[8, 9, 6, 4, 7]
m2 [6, 4, 7, 8, 9]


In [43]:
# find the sum of all possible pairs in nth array
# a={1,2}
#o/p=12
#(1,1)(1,2)(2,1)(2,2)

#m1
a=[]
n=int(input("how many  : "))
for i in range(n):
    a.append(int(input('enter  : ')))
print(a)    
def summ(arr):
    n=len(arr)
    s=0
    for i in range(n):
        for j in range(n):
            s+=arr[i]+arr[j]
    return  s
x=summ(a)
print(x)
#m2
def summ1(a):
    n=len(a)
    s=0
    for i in range(n):
        s=s+(a[i]*(2*n))
    return s
y=summ1(a)
print(y)

how many  : 3
enter  : 4
enter  : 5
enter  : 6
[4, 5, 6]
90
90


In [5]:
# program to cyclically rotate an array by one
a=[]
n=int(input("how many  : "))
for i in range(n):
    a.append(int(input('enter  : ')))
print(a)  
# rotation
temp=a[0]
for i in range(n-1):
    a[i]=a[i+1]
a[n-1]=temp 
print(a)

how many  : 5
enter  : 1
enter  : 2
enter  : 3
enter  : 4
enter  : 5
[1, 2, 3, 4, 5]
1
[2, 3, 4, 5, 1]


In [3]:
# Python 3 program to count frequencies 
# of array items 
def countFreq(arr, n): 
      
    # Mark all array elements as not visited 
    visited = [False for i in range(n)]
    #visited = [False]*n
  
    # Traverse through array elements  
    # and count frequencies 
    for i in range(n): 
          
        # Skip this element if already  
        # processed 
        if (visited[i] == True): 
            continue
  
        # Count frequency 
        count = 1
        for j in range(i + 1, n, 1): 
            if (arr[i] == arr[j]): 
                visited[j] = True
                count += 1
          
        print(arr[i], count) 
  
# Driver Code 
if __name__ == '__main__': 
    arr = [10, 20, 20, 10, 10, 20, 5, 20] 
    n = len(arr) 
    countFreq(arr, n) 

10 3
20 4
5 1


# SUBARRAY WITH GIEVN SUM

In [40]:
#t = int(input("enter test case: "))

m, n =[int(x) for x in input(" enter size and sum:  ").split(" ")]

a=[]
for i in range(m):
    a.append(int(input("enter elements:  ")))
    
def subarray(a):
    l = len(a)
    flag=False
    for i in range(l):
        j =i
        s=0
        print("j= ",j)
        while(j < l):
            s=s+a[j]
            if s==n:
                print(i+1, j+1)
                flag=True
                break
            j=j+1
        if flag==True:
            break
        print("inc")    
            
                  
subarray(a)       

 enter size and sum:  5 12
enter elements:  1
enter elements:  2
enter elements:  3
enter elements:  7
enter elements:  5
j=  0
inc
j=  1
2 4


In [44]:
t= int(input("enter testcases:  "))
for i in range(t):
    m, n =[int(x) for x in input(" enter size and sum:  ").split(" ")]


    s=input()
    a=[]
    for i in s:
        a.append(int(i)) 
    
    def subarray(a):
        l = len(a)
        flag=False
        for i in range(l): 
            j=i
            s=0
            while(j<l):
                s=s+a[j]
                if s==n:
                    print(i+1, j+1)
                    flag=True
                    break
                j=j+1
            if flag==True:
                break
    subarray(a)     

enter testcases:  2
 enter size and sum:  5 12
12375
2 4
 enter size and sum:  10 15
12345678910
1 5


In [47]:
n = map(int, input().split(" "))
a=list(n)
print(a)

1 2 3
[1, 2, 3]


In [51]:
t= int(input(  ))
for i in range(t):
    m, n =[int(x) for x in input( ).split(" ")]


    s=map(int, input().split(" "))
    a=list(s)
    def subarray(a):
        l = m
        flag=False
        for i in range(l): 
            j=i
            s=0
            while(j<l):
                s=s+a[j]
                if s==n:
                    print(i+1, j+1)
                    flag=True
                    break
                j=j+1
            if flag==True:
                break
    subarray(a)     

1
5 12
1 2 3 7 5
2 4


# Given an array of distinct integers. The task is to count all the triplets such that sum of two elements equals the third element.

In [11]:
n=int(input("enter testcases: "))

for i in range(n):
    l = int(input("enter size: "))
    s=map(int, input("enter elements wuith space separated: ").split(" "))
    a=list(s)
    c=0
    for i in range(l):
        x=a[i]
        p = a.index(x)
        while p<l:
            s=x+a[p]
            print("sss", s)
            if s in a:
                print('cccc', c)
                c=c+1
            s=0
            p=p+1
    if c>0:
        print(c-1)
    else:
        print(-1)
           

enter testcases: 1
enter size: 4
enter elements wuith space separated: 1 5 3 2
sss 2
cccc 0
sss 6
sss 4
sss 3
cccc 1
sss 10
sss 8
sss 7
sss 6
sss 5
cccc 0
sss 4
-1
